### ISSUE TITLE
Russell: Change colour palette? (and link colour)

### ISSUE THREAD

**Issue by ashendruk** [ashendruk/comics#17]
You mentioned last week that you might want colours changed. Do you have a set of preferred colours? Let me know! Otherwise I can go looking around for a different palette.

**Comment by russellsamora** [comment]
did the person who make the gifs have a palette? if you could send that it would be a good starting point.

**Comment by ashendruk** [comment]
Yeah. It's the same palette I used throughout. But I can send to you if you want

**Comment by ashendruk** [comment]
Here it is: https://s-media-cache-ak0.pinimg.com/originals/36/06/bc/3606bcdd47f06d1d520ec8ca19fa3256.jpg

**Comment by russellsamora** [comment]
Oh i meant her full palette, the gifs have way more colors if she has it.

**Comment by ashendruk** [comment]
I'll see if she has one ....

**Comment by ashendruk** [comment]
She doesn't have one :( So, how do you want to proceed with colours?

**Comment by russellsamora** [comment]
maybe ill play around a bit with it
