### ISSUE TITLE
label and add % on first chart axis

### ISSUE THREAD

**Issue by russellsamora** [ashendruk/comics#21]

**Comment by ashendruk** [comment]
Do you think this will confuse people? I don't want them thinking it's a percent difference. It's a point difference, technically. I think generally people don't put the percent when it's just the absolute difference. I'll take a look at some polling charts, but I think it might not be correct to add the percentage sign

**Comment by ashendruk** [comment]
Yeah, here's an example from the economist. https://twitter.com/ECONdailycharts/status/879960757311606784
So I won't add the % sign, but I will add the label of % pts
