### ISSUE TITLE
first chart category labels should be centered

### ISSUE THREAD

**Issue by russellsamora** [ashendruk/comics#27]

**Comment by ashendruk** [comment]
Do you know how to do this? I'm not sure why, but I couldn't figure it out earlier. I feel like it should be really easy, but I just haven't hit on the correct line of code. Have you done this before and happen to know how? If not, I'll keep working on it myself. Just thought you might have an idea.

**Comment by russellsamora** [comment]
use the text-anchor attribute https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-anchor

**Comment by ashendruk** [comment]
Ok. I tried that but I guess I wasn't implementing it properly. I'll fiddle with it again.
