### ISSUE TITLE
second chart annotations overlap 

### ISSUE THREAD

**Issue by russellsamora** [ashendruk/comics#34]

**Comment by ashendruk** [comment]
On the teams chart or the gender chart? I don't see overlapping on either ... ? What browser or page width are you using? ('cause it's not responsive yet)

**Comment by russellsamora** [comment]
https://i.imgur.com/N08aIkg.png

**Comment by ashendruk** [comment]
Oh! Ok. That's a function of the sorting not working correctly in Chrome. That will fix once I get the sort to work right.

**Comment by ashendruk** [comment]
Will be fixed when sorting on chart is fixed
