### ISSUE TITLE
second chart put lines behind circles

### ISSUE THREAD

**Issue by russellsamora** [ashendruk/comics#35]

**Comment by ashendruk** [comment]
Any suggestions on how to do this, Russell? I know z-index doesn't work for svg ... but i can't figure out a way to bring just the lines to front. Thoughts?

**Comment by russellsamora** [comment]
its just the order which you append things to the dom, so add that group or line item before the circles

**Comment by ashendruk** [comment]
Oh wow. That was easy! lol
