### ISSUE TITLE
tristan's feedback

### ISSUE THREAD

**Issue by russellsamora** [ashendruk/comics#47]
just making sure you had a chance to see it and consider his thoughts:

Okay.  So, Amanda's comic book piece that you sent me is really phenomenal.  There's really just not all that much work on comics that utilizes some of the big data available to us now - beyond some of the smart things being done in data journalism.  Walt Hickey for FiveThirtyEight has written a couple posts like this, but this is much more extensive, and I like that it engages experts in the field.

One issue that is not really addressed in the article, but is something my partner and I have talked about before regarding women superheroes is that they seem like they might be more likely to be depicted as out of control of their powers when they are given powers on par with powerful men characters (like Jean Grey and Rogue).  This may be more of how they are depicted in film than comic books. But it might be an interesting way of discussing the ways that even really powerful women characters are sometimes symbolically disempowered in this way.

Another issue not addressed in the piece but that it seems like data must exist on is size discrepancies.  I wrote a piece on this issue in Pixar films, and I'd imagine the same critique is relevant here - male characters are depicted as MUCH larger than female characters.  I wonder if there are data on character size that would enable you to make this a data-based argument here.  Here's my post on Pixar if you're interested: https://inequalitybyinteriordesign.wordpress.com/2014/09/11/barrel-chests-brawn-and-buffoonery-controlling-images-of-masculinity-in-pixar-movies/

These were the two things I felt could have been added, or considered.  My bullshit meter never went off reading it.  I wasn't bored either.  There are a few small edits: " Carolyn Cocca, academic and author of the Eisner-nominated book "Superwomen: Gender, Power, and Representation", says this data is inline with what she has seen in her research." This should read "in line," not "inline."

Lastly, I think it's important to talk about "progress" in comics in perspective. There are, for instance, a higher proportion of female super heroes in both Marvel and DC universes than there are women in Congress in the U.S.  That's important to consider - science fiction and fantasy are often "describing" society as much as "prescribing" new societies. So, turning the lens around to ask what this might say about the type of society that would produce these data could be an interesting thought experiment to consider somewhere in the conclusion.  Just an idea.

Also, some of the interactivity from the Wonder Woman avatar providing explanations of the data (which is so neat) does not work. She lists information for some of the data points, and not others.  Perhaps you know this.  I just thought I'd mention it.

Let me know if I can provide anything else.  It's a really fantastic piece.  I can't wait to see the finished version.

**Comment by ashendruk** [comment]
I did! I was going to work a few of his thoughts in tonight. He's suggesting some things that are out of the scope of this project, but I'll touch on a few of his thoughts.

**Comment by ashendruk** [comment]
So, he mentions he likes the fact that I had 'experts' in the piece. But now I've taken out most of the expert stuff. I left one quote - at the end. I could either go this way, OR I could search for a few other experts and add the expert stuff back in, but only use one quote from each. I got the impression, though, that you and Ilia weren't really into the quotes. Felt too middle-school essay.

**Comment by russellsamora** [comment]
we weren't necessarily against all the quotes, but the way they were used, and the way she was framed as the only expert. i haven't read the latest, but part of the thought is it should bring something new to your prose and be worked in to the setup / analysis, rather than a "this person also agrees" tacked on the end.
