### ISSUE TITLE
what happened to clippy?

### ISSUE THREAD

**Issue by russellsamora** [ashendruk/comics#59]
she doesn't show up anymore

**Comment by ashendruk** [comment]
She shows up if your screen is wide enough. You didn't want her to conflict with the charts

**Comment by ashendruk** [comment]
I do see now though that she's showing up a touch low for the last chart

**Comment by russellsamora** [comment]
oh i assumed it would work on standard laptop (im on a macbook, i think 1280px). I would adjust the charts so it works smaller, otherwise basically no one will see it.

**Comment by ashendruk** [comment]
okey dokey
